const Bus = require('../models/Bus');

// Helper: get a date string N days from now
const daysFromNow = (n) => {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d.toISOString().split('T')[0];
};

// We create buses for multiple upcoming dates so any date the user picks works
const createBuses = () => [
  // ── NAIROBI → MOMBASA ──────────────────────────────────────────
  {
    name: 'Modern Coast Express',
    busNumber: 'KCB 123A', type: 'AC', fare: 1200,
    numberOfSeats: 44, seatsAvailable: 44,
    seatsConfiguration: { left: 2, right: 2 },
    boardingPoints: ['Nairobi CBD', 'Westlands'],
    droppingPoints: ['Voi', 'Mombasa CBD'],
    features: ['WiFi', 'AC', 'USB Charging', 'Reclining Seats'],
    description: 'Luxury coach Nairobi to Mombasa',
    departure_time: '08:00 AM',
    journeyDate: daysFromNow(1),
    isAvailable: true, bookedSeat: [], soldSeat: [],
    slug: 'modern-coast-express-d1',
  },
  {
    name: 'Modern Coast Express',
    busNumber: 'KCB 123A', type: 'AC', fare: 1200,
    numberOfSeats: 44, seatsAvailable: 44,
    seatsConfiguration: { left: 2, right: 2 },
    boardingPoints: ['Nairobi CBD', 'Westlands'],
    droppingPoints: ['Voi', 'Mombasa CBD'],
    features: ['WiFi', 'AC', 'USB Charging', 'Reclining Seats'],
    description: 'Luxury coach Nairobi to Mombasa',
    departure_time: '08:00 AM',
    journeyDate: daysFromNow(2),
    isAvailable: true, bookedSeat: [], soldSeat: [],
    slug: 'modern-coast-express-d2',
  },
  {
    name: 'Modern Coast Express',
    busNumber: 'KCB 123A', type: 'AC', fare: 1200,
    numberOfSeats: 44, seatsAvailable: 44,
    seatsConfiguration: { left: 2, right: 2 },
    boardingPoints: ['Nairobi CBD', 'Westlands'],
    droppingPoints: ['Voi', 'Mombasa CBD'],
    features: ['WiFi', 'AC', 'USB Charging', 'Reclining Seats'],
    description: 'Luxury coach Nairobi to Mombasa',
    departure_time: '08:00 AM',
    journeyDate: daysFromNow(3),
    isAvailable: true, bookedSeat: [], soldSeat: [],
    slug: 'modern-coast-express-d3',
  },
  {
    name: 'Modern Coast Express',
    busNumber: 'KCB 123A', type: 'AC', fare: 1200,
    numberOfSeats: 44, seatsAvailable: 44,
    seatsConfiguration: { left: 2, right: 2 },
    boardingPoints: ['Nairobi CBD', 'Westlands'],
    droppingPoints: ['Voi', 'Mombasa CBD'],
    features: ['WiFi', 'AC', 'USB Charging', 'Reclining Seats'],
    description: 'Luxury coach Nairobi to Mombasa',
    departure_time: '08:00 AM',
    journeyDate: daysFromNow(4),
    isAvailable: true, bookedSeat: [], soldSeat: [],
    slug: 'modern-coast-express-d4',
  },
  {
    name: 'Modern Coast Express',
    busNumber: 'KCB 123A', type: 'AC', fare: 1200,
    numberOfSeats: 44, seatsAvailable: 44,
    seatsConfiguration: { left: 2, right: 2 },
    boardingPoints: ['Nairobi CBD', 'Westlands'],
    droppingPoints: ['Voi', 'Mombasa CBD'],
    features: ['WiFi', 'AC', 'USB Charging', 'Reclining Seats'],
    description: 'Luxury coach Nairobi to Mombasa',
    departure_time: '08:00 AM',
    journeyDate: daysFromNow(5),
    isAvailable: true, bookedSeat: [], soldSeat: [],
    slug: 'modern-coast-express-d5',
  },
  {
    name: 'Modern Coast Night Rider',
    busNumber: 'KCB 124A', type: 'AC', fare: 1300,
    numberOfSeats: 44, seatsAvailable: 44,
    seatsConfiguration: { left: 2, right: 2 },
    boardingPoints: ['Nairobi CBD', 'Westlands'],
    droppingPoints: ['Voi', 'Mombasa CBD'],
    features: ['WiFi', 'AC', 'Blanket Provided', 'Reclining Seats'],
    description: 'Overnight luxury coach Nairobi to Mombasa',
    departure_time: '09:00 PM',
    journeyDate: daysFromNow(1),
    isAvailable: true, bookedSeat: [], soldSeat: [],
    slug: 'modern-coast-night-d1',
  },
  {
    name: 'Modern Coast Night Rider',
    busNumber: 'KCB 124A', type: 'AC', fare: 1300,
    numberOfSeats: 44, seatsAvailable: 44,
    seatsConfiguration: { left: 2, right: 2 },
    boardingPoints: ['Nairobi CBD', 'Westlands'],
    droppingPoints: ['Voi', 'Mombasa CBD'],
    features: ['WiFi', 'AC', 'Blanket Provided', 'Reclining Seats'],
    description: 'Overnight luxury coach Nairobi to Mombasa',
    departure_time: '09:00 PM',
    journeyDate: daysFromNow(2),
    isAvailable: true, bookedSeat: [], soldSeat: [],
    slug: 'modern-coast-night-d2',
  },
  {
    name: 'Modern Coast Night Rider',
    busNumber: 'KCB 124A', type: 'AC', fare: 1300,
    numberOfSeats: 44, seatsAvailable: 44,
    seatsConfiguration: { left: 2, right: 2 },
    boardingPoints: ['Nairobi CBD', 'Westlands'],
    droppingPoints: ['Voi', 'Mombasa CBD'],
    features: ['WiFi', 'AC', 'Blanket Provided', 'Reclining Seats'],
    description: 'Overnight luxury coach Nairobi to Mombasa',
    departure_time: '09:00 PM',
    journeyDate: daysFromNow(3),
    isAvailable: true, bookedSeat: [], soldSeat: [],
    slug: 'modern-coast-night-d3',
  },
  {
    name: 'Modern Coast Night Rider',
    busNumber: 'KCB 124A', type: 'AC', fare: 1300,
    numberOfSeats: 44, seatsAvailable: 44,
    seatsConfiguration: { left: 2, right: 2 },
    boardingPoints: ['Nairobi CBD', 'Westlands'],
    droppingPoints: ['Voi', 'Mombasa CBD'],
    features: ['WiFi', 'AC', 'Blanket Provided', 'Reclining Seats'],
    description: 'Overnight luxury coach Nairobi to Mombasa',
    departure_time: '09:00 PM',
    journeyDate: daysFromNow(4),
    isAvailable: true, bookedSeat: [], soldSeat: [],
    slug: 'modern-coast-night-d4',
  },
  {
    name: 'Modern Coast Night Rider',
    busNumber: 'KCB 124A', type: 'AC', fare: 1300,
    numberOfSeats: 44, seatsAvailable: 44,
    seatsConfiguration: { left: 2, right: 2 },
    boardingPoints: ['Nairobi CBD', 'Westlands'],
    droppingPoints: ['Voi', 'Mombasa CBD'],
    features: ['WiFi', 'AC', 'Blanket Provided', 'Reclining Seats'],
    description: 'Overnight luxury coach Nairobi to Mombasa',
    departure_time: '09:00 PM',
    journeyDate: daysFromNow(5),
    isAvailable: true, bookedSeat: [], soldSeat: [],
    slug: 'modern-coast-night-d5',
  },
  {
    name: 'Easy Coach Morning',
    busNumber: 'KDB 456B', type: 'Delux', fare: 950,
    numberOfSeats: 52, seatsAvailable: 52,
    seatsConfiguration: { left: 2, right: 2 },
    boardingPoints: ['Nairobi CBD', 'Thika'],
    droppingPoints: ['Kilifi', 'Mombasa CBD'],
    features: ['AC', 'Water Provided', 'Comfortable Seats'],
    description: 'Morning service Nairobi to Mombasa',
    departure_time: '06:30 AM',
    journeyDate: daysFromNow(1),
    isAvailable: true, bookedSeat: [], soldSeat: [],
    slug: 'easy-coach-morning-d1',
  },
  {
    name: 'Easy Coach Morning',
    busNumber: 'KDB 456B', type: 'Delux', fare: 950,
    numberOfSeats: 52, seatsAvailable: 52,
    seatsConfiguration: { left: 2, right: 2 },
    boardingPoints: ['Nairobi CBD', 'Thika'],
    droppingPoints: ['Kilifi', 'Mombasa CBD'],
    features: ['AC', 'Water Provided', 'Comfortable Seats'],
    description: 'Morning service Nairobi to Mombasa',
    departure_time: '06:30 AM',
    journeyDate: daysFromNow(2),
    isAvailable: true, bookedSeat: [], soldSeat: [],
    slug: 'easy-coach-morning-d2',
  },
  {
    name: 'Easy Coach Morning',
    busNumber: 'KDB 456B', type: 'Delux', fare: 950,
    numberOfSeats: 52, seatsAvailable: 52,
    seatsConfiguration: { left: 2, right: 2 },
    boardingPoints: ['Nairobi CBD', 'Thika'],
    droppingPoints: ['Kilifi', 'Mombasa CBD'],
    features: ['AC', 'Water Provided', 'Comfortable Seats'],
    description: 'Morning service Nairobi to Mombasa',
    departure_time: '06:30 AM',
    journeyDate: daysFromNow(3),
    isAvailable: true, bookedSeat: [], soldSeat: [],
    slug: 'easy-coach-morning-d3',
  },
  {
    name: 'Easy Coach Morning',
    busNumber: 'KDB 456B', type: 'Delux', fare: 950,
    numberOfSeats: 52, seatsAvailable: 52,
    seatsConfiguration: { left: 2, right: 2 },
    boardingPoints: ['Nairobi CBD', 'Thika'],
    droppingPoints: ['Kilifi', 'Mombasa CBD'],
    features: ['AC', 'Water Provided', 'Comfortable Seats'],
    description: 'Morning service Nairobi to Mombasa',
    departure_time: '06:30 AM',
    journeyDate: daysFromNow(4),
    isAvailable: true, bookedSeat: [], soldSeat: [],
    slug: 'easy-coach-morning-d4',
  },
  {
    name: 'Easy Coach Morning',
    busNumber: 'KDB 456B', type: 'Delux', fare: 950,
    numberOfSeats: 52, seatsAvailable: 52,
    seatsConfiguration: { left: 2, right: 2 },
    boardingPoints: ['Nairobi CBD', 'Thika'],
    droppingPoints: ['Kilifi', 'Mombasa CBD'],
    features: ['AC', 'Water Provided', 'Comfortable Seats'],
    description: 'Morning service Nairobi to Mombasa',
    departure_time: '06:30 AM',
    journeyDate: daysFromNow(5),
    isAvailable: true, bookedSeat: [], soldSeat: [],
    slug: 'easy-coach-morning-d5',
  },
  {
    name: 'Easy Coach Afternoon',
    busNumber: 'KDB 457B', type: 'Delux', fare: 950,
    numberOfSeats: 52, seatsAvailable: 52,
    seatsConfiguration: { left: 2, right: 2 },
    boardingPoints: ['Nairobi CBD', 'Thika'],
    droppingPoints: ['Kilifi', 'Mombasa CBD'],
    features: ['AC', 'Water Provided', 'Comfortable Seats'],
    description: 'Afternoon service Nairobi to Mombasa',
    departure_time: '02:00 PM',
    journeyDate: daysFromNow(1),
    isAvailable: true, bookedSeat: [], soldSeat: [],
    slug: 'easy-coach-afternoon-d1',
  },
  {
    name: 'Easy Coach Afternoon',
    busNumber: 'KDB 457B', type: 'Delux', fare: 950,
    numberOfSeats: 52, seatsAvailable: 52,
    seatsConfiguration: { left: 2, right: 2 },
    boardingPoints: ['Nairobi CBD', 'Thika'],
    droppingPoints: ['Kilifi', 'Mombasa CBD'],
    features: ['AC', 'Water Provided', 'Comfortable Seats'],
    description: 'Afternoon service Nairobi to Mombasa',
    departure_time: '02:00 PM',
    journeyDate: daysFromNow(2),
    isAvailable: true, bookedSeat: [], soldSeat: [],
    slug: 'easy-coach-afternoon-d2',
  },
  {
    name: 'Easy Coach Afternoon',
    busNumber: 'KDB 457B', type: 'Delux', fare: 950,
    numberOfSeats: 52, seatsAvailable: 52,
    seatsConfiguration: { left: 2, right: 2 },
    boardingPoints: ['Nairobi CBD', 'Thika'],
    droppingPoints: ['Kilifi', 'Mombasa CBD'],
    features: ['AC', 'Water Provided', 'Comfortable Seats'],
    description: 'Afternoon service Nairobi to Mombasa',
    departure_time: '02:00 PM',
    journeyDate: daysFromNow(3),
    isAvailable: true, bookedSeat: [], soldSeat: [],
    slug: 'easy-coach-afternoon-d3',
  },
  {
    name: 'Easy Coach Afternoon',
    busNumber: 'KDB 457B', type: 'Delux', fare: 950,
    numberOfSeats: 52, seatsAvailable: 52,
    seatsConfiguration: { left: 2, right: 2 },
    boardingPoints: ['Nairobi CBD', 'Thika'],
    droppingPoints: ['Kilifi', 'Mombasa CBD'],
    features: ['AC', 'Water Provided', 'Comfortable Seats'],
    description: 'Afternoon service Nairobi to Mombasa',
    departure_time: '02:00 PM',
    journeyDate: daysFromNow(4),
    isAvailable: true, bookedSeat: [], soldSeat: [],
    slug: 'easy-coach-afternoon-d4',
  },
  {
    name: 'Easy Coach Afternoon',
    busNumber: 'KDB 457B', type: 'Delux', fare: 950,
    numberOfSeats: 52, seatsAvailable: 52,
    seatsConfiguration: { left: 2, right: 2 },
    boardingPoints: ['Nairobi CBD', 'Thika'],
    droppingPoints: ['Kilifi', 'Mombasa CBD'],
    features: ['AC', 'Water Provided', 'Comfortable Seats'],
    description: 'Afternoon service Nairobi to Mombasa',
    departure_time: '02:00 PM',
    journeyDate: daysFromNow(5),
    isAvailable: true, bookedSeat: [], soldSeat: [],
    slug: 'easy-coach-afternoon-d5',
  },
  // ── NAIROBI → KISUMU ───────────────────────────────────────────
  {
    name: 'Transline Classic',
    busNumber: 'KDA 789C', type: 'Normal', fare: 800,
    numberOfSeats: 52, seatsAvailable: 52,
    seatsConfiguration: { left: 2, right: 2 },
    boardingPoints: ['Nairobi CBD'],
    droppingPoints: ['Nakuru', 'Kericho', 'Kisumu'],
    features: ['AC', 'Legroom'],
    description: 'Nairobi to Kisumu via Nakuru',
    departure_time: '07:00 AM',
    journeyDate: daysFromNow(1),
    isAvailable: true, bookedSeat: [], soldSeat: [],
    slug: 'transline-classic-d1',
  },
  {
    name: 'Transline Classic',
    busNumber: 'KDA 789C', type: 'Normal', fare: 800,
    numberOfSeats: 52, seatsAvailable: 52,
    seatsConfiguration: { left: 2, right: 2 },
    boardingPoints: ['Nairobi CBD'],
    droppingPoints: ['Nakuru', 'Kericho', 'Kisumu'],
    features: ['AC', 'Legroom'],
    description: 'Nairobi to Kisumu via Nakuru',
    departure_time: '07:00 AM',
    journeyDate: daysFromNow(2),
    isAvailable: true, bookedSeat: [], soldSeat: [],
    slug: 'transline-classic-d2',
  },
  {
    name: 'Transline Classic',
    busNumber: 'KDA 789C', type: 'Normal', fare: 800,
    numberOfSeats: 52, seatsAvailable: 52,
    seatsConfiguration: { left: 2, right: 2 },
    boardingPoints: ['Nairobi CBD'],
    droppingPoints: ['Nakuru', 'Kericho', 'Kisumu'],
    features: ['AC', 'Legroom'],
    description: 'Nairobi to Kisumu via Nakuru',
    departure_time: '07:00 AM',
    journeyDate: daysFromNow(3),
    isAvailable: true, bookedSeat: [], soldSeat: [],
    slug: 'transline-classic-d3',
  },
  {
    name: 'Transline Classic',
    busNumber: 'KDA 789C', type: 'Normal', fare: 800,
    numberOfSeats: 52, seatsAvailable: 52,
    seatsConfiguration: { left: 2, right: 2 },
    boardingPoints: ['Nairobi CBD'],
    droppingPoints: ['Nakuru', 'Kericho', 'Kisumu'],
    features: ['AC', 'Legroom'],
    description: 'Nairobi to Kisumu via Nakuru',
    departure_time: '07:00 AM',
    journeyDate: daysFromNow(4),
    isAvailable: true, bookedSeat: [], soldSeat: [],
    slug: 'transline-classic-d4',
  },
  {
    name: 'Transline Classic',
    busNumber: 'KDA 789C', type: 'Normal', fare: 800,
    numberOfSeats: 52, seatsAvailable: 52,
    seatsConfiguration: { left: 2, right: 2 },
    boardingPoints: ['Nairobi CBD'],
    droppingPoints: ['Nakuru', 'Kericho', 'Kisumu'],
    features: ['AC', 'Legroom'],
    description: 'Nairobi to Kisumu via Nakuru',
    departure_time: '07:00 AM',
    journeyDate: daysFromNow(5),
    isAvailable: true, bookedSeat: [], soldSeat: [],
    slug: 'transline-classic-d5',
  },
  // ── NAIROBI → ELDORET ──────────────────────────────────────────
  {
    name: 'Mash East Africa',
    busNumber: 'KCA 321D', type: 'Suspense AC', fare: 900,
    numberOfSeats: 44, seatsAvailable: 44,
    seatsConfiguration: { left: 2, right: 2 },
    boardingPoints: ['Nairobi CBD', 'Westlands'],
    droppingPoints: ['Nakuru', 'Eldoret'],
    features: ['Suspense AC', 'WiFi', 'Charging Ports'],
    description: 'Premium Nairobi to Eldoret service',
    departure_time: '08:30 AM',
    journeyDate: daysFromNow(1),
    isAvailable: true, bookedSeat: [], soldSeat: [],
    slug: 'mash-east-africa-d1',
  },
  {
    name: 'Mash East Africa',
    busNumber: 'KCA 321D', type: 'Suspense AC', fare: 900,
    numberOfSeats: 44, seatsAvailable: 44,
    seatsConfiguration: { left: 2, right: 2 },
    boardingPoints: ['Nairobi CBD', 'Westlands'],
    droppingPoints: ['Nakuru', 'Eldoret'],
    features: ['Suspense AC', 'WiFi', 'Charging Ports'],
    description: 'Premium Nairobi to Eldoret service',
    departure_time: '08:30 AM',
    journeyDate: daysFromNow(2),
    isAvailable: true, bookedSeat: [], soldSeat: [],
    slug: 'mash-east-africa-d2',
  },
  {
    name: 'Mash East Africa',
    busNumber: 'KCA 321D', type: 'Suspense AC', fare: 900,
    numberOfSeats: 44, seatsAvailable: 44,
    seatsConfiguration: { left: 2, right: 2 },
    boardingPoints: ['Nairobi CBD', 'Westlands'],
    droppingPoints: ['Nakuru', 'Eldoret'],
    features: ['Suspense AC', 'WiFi', 'Charging Ports'],
    description: 'Premium Nairobi to Eldoret service',
    departure_time: '08:30 AM',
    journeyDate: daysFromNow(3),
    isAvailable: true, bookedSeat: [], soldSeat: [],
    slug: 'mash-east-africa-d3',
  },
  {
    name: 'Mash East Africa',
    busNumber: 'KCA 321D', type: 'Suspense AC', fare: 900,
    numberOfSeats: 44, seatsAvailable: 44,
    seatsConfiguration: { left: 2, right: 2 },
    boardingPoints: ['Nairobi CBD', 'Westlands'],
    droppingPoints: ['Nakuru', 'Eldoret'],
    features: ['Suspense AC', 'WiFi', 'Charging Ports'],
    description: 'Premium Nairobi to Eldoret service',
    departure_time: '08:30 AM',
    journeyDate: daysFromNow(4),
    isAvailable: true, bookedSeat: [], soldSeat: [],
    slug: 'mash-east-africa-d4',
  },
  {
    name: 'Mash East Africa',
    busNumber: 'KCA 321D', type: 'Suspense AC', fare: 900,
    numberOfSeats: 44, seatsAvailable: 44,
    seatsConfiguration: { left: 2, right: 2 },
    boardingPoints: ['Nairobi CBD', 'Westlands'],
    droppingPoints: ['Nakuru', 'Eldoret'],
    features: ['Suspense AC', 'WiFi', 'Charging Ports'],
    description: 'Premium Nairobi to Eldoret service',
    departure_time: '08:30 AM',
    journeyDate: daysFromNow(5),
    isAvailable: true, bookedSeat: [], soldSeat: [],
    slug: 'mash-east-africa-d5',
  },
  // ── MOMBASA → MALINDI ──────────────────────────────────────────
  {
    name: 'Guardian Angel Bus',
    busNumber: 'KBZ 555E', type: 'Normal', fare: 1500,
    numberOfSeats: 44, seatsAvailable: 44,
    seatsConfiguration: { left: 2, right: 2 },
    boardingPoints: ['Mombasa CBD', 'Nyali'],
    droppingPoints: ['Kilifi', 'Malindi'],
    features: ['Comfortable Seats', 'Storage Space'],
    description: 'Mombasa to Malindi coastal route',
    departure_time: '09:00 AM',
    journeyDate: daysFromNow(1),
    isAvailable: true, bookedSeat: [], soldSeat: [],
    slug: 'guardian-angel-d1',
  },
  {
    name: 'Guardian Angel Bus',
    busNumber: 'KBZ 555E', type: 'Normal', fare: 1500,
    numberOfSeats: 44, seatsAvailable: 44,
    seatsConfiguration: { left: 2, right: 2 },
    boardingPoints: ['Mombasa CBD', 'Nyali'],
    droppingPoints: ['Kilifi', 'Malindi'],
    features: ['Comfortable Seats', 'Storage Space'],
    description: 'Mombasa to Malindi coastal route',
    departure_time: '09:00 AM',
    journeyDate: daysFromNow(2),
    isAvailable: true, bookedSeat: [], soldSeat: [],
    slug: 'guardian-angel-d2',
  },
  {
    name: 'Guardian Angel Bus',
    busNumber: 'KBZ 555E', type: 'Normal', fare: 1500,
    numberOfSeats: 44, seatsAvailable: 44,
    seatsConfiguration: { left: 2, right: 2 },
    boardingPoints: ['Mombasa CBD', 'Nyali'],
    droppingPoints: ['Kilifi', 'Malindi'],
    features: ['Comfortable Seats', 'Storage Space'],
    description: 'Mombasa to Malindi coastal route',
    departure_time: '09:00 AM',
    journeyDate: daysFromNow(3),
    isAvailable: true, bookedSeat: [], soldSeat: [],
    slug: 'guardian-angel-d3',
  },
  {
    name: 'Guardian Angel Bus',
    busNumber: 'KBZ 555E', type: 'Normal', fare: 1500,
    numberOfSeats: 44, seatsAvailable: 44,
    seatsConfiguration: { left: 2, right: 2 },
    boardingPoints: ['Mombasa CBD', 'Nyali'],
    droppingPoints: ['Kilifi', 'Malindi'],
    features: ['Comfortable Seats', 'Storage Space'],
    description: 'Mombasa to Malindi coastal route',
    departure_time: '09:00 AM',
    journeyDate: daysFromNow(4),
    isAvailable: true, bookedSeat: [], soldSeat: [],
    slug: 'guardian-angel-d4',
  },
  {
    name: 'Guardian Angel Bus',
    busNumber: 'KBZ 555E', type: 'Normal', fare: 1500,
    numberOfSeats: 44, seatsAvailable: 44,
    seatsConfiguration: { left: 2, right: 2 },
    boardingPoints: ['Mombasa CBD', 'Nyali'],
    droppingPoints: ['Kilifi', 'Malindi'],
    features: ['Comfortable Seats', 'Storage Space'],
    description: 'Mombasa to Malindi coastal route',
    departure_time: '09:00 AM',
    journeyDate: daysFromNow(5),
    isAvailable: true, bookedSeat: [], soldSeat: [],
    slug: 'guardian-angel-d5',
  },
  // ── NAIROBI → NYERI ────────────────────────────────────────────
  {
    name: '2NK Shuttle',
    busNumber: 'KCE 777F', type: 'Delux', fare: 600,
    numberOfSeats: 29, seatsAvailable: 29,
    seatsConfiguration: { left: 2, right: 1 },
    boardingPoints: ['Nairobi CBD', 'Thika'],
    droppingPoints: ['Nanyuki', 'Nyeri'],
    features: ['AC', 'Fast Service'],
    description: 'Quick shuttle to central Kenya',
    departure_time: '07:30 AM',
    journeyDate: daysFromNow(1),
    isAvailable: true, bookedSeat: [], soldSeat: [],
    slug: '2nk-shuttle-d1',
  },
  {
    name: '2NK Shuttle',
    busNumber: 'KCE 777F', type: 'Delux', fare: 600,
    numberOfSeats: 29, seatsAvailable: 29,
    seatsConfiguration: { left: 2, right: 1 },
    boardingPoints: ['Nairobi CBD', 'Thika'],
    droppingPoints: ['Nanyuki', 'Nyeri'],
    features: ['AC', 'Fast Service'],
    description: 'Quick shuttle to central Kenya',
    departure_time: '07:30 AM',
    journeyDate: daysFromNow(2),
    isAvailable: true, bookedSeat: [], soldSeat: [],
    slug: '2nk-shuttle-d2',
  },
  {
    name: '2NK Shuttle',
    busNumber: 'KCE 777F', type: 'Delux', fare: 600,
    numberOfSeats: 29, seatsAvailable: 29,
    seatsConfiguration: { left: 2, right: 1 },
    boardingPoints: ['Nairobi CBD', 'Thika'],
    droppingPoints: ['Nanyuki', 'Nyeri'],
    features: ['AC', 'Fast Service'],
    description: 'Quick shuttle to central Kenya',
    departure_time: '07:30 AM',
    journeyDate: daysFromNow(3),
    isAvailable: true, bookedSeat: [], soldSeat: [],
    slug: '2nk-shuttle-d3',
  },
  {
    name: '2NK Shuttle',
    busNumber: 'KCE 777F', type: 'Delux', fare: 600,
    numberOfSeats: 29, seatsAvailable: 29,
    seatsConfiguration: { left: 2, right: 1 },
    boardingPoints: ['Nairobi CBD', 'Thika'],
    droppingPoints: ['Nanyuki', 'Nyeri'],
    features: ['AC', 'Fast Service'],
    description: 'Quick shuttle to central Kenya',
    departure_time: '07:30 AM',
    journeyDate: daysFromNow(4),
    isAvailable: true, bookedSeat: [], soldSeat: [],
    slug: '2nk-shuttle-d4',
  },
  {
    name: '2NK Shuttle',
    busNumber: 'KCE 777F', type: 'Delux', fare: 600,
    numberOfSeats: 29, seatsAvailable: 29,
    seatsConfiguration: { left: 2, right: 1 },
    boardingPoints: ['Nairobi CBD', 'Thika'],
    droppingPoints: ['Nanyuki', 'Nyeri'],
    features: ['AC', 'Fast Service'],
    description: 'Quick shuttle to central Kenya',
    departure_time: '07:30 AM',
    journeyDate: daysFromNow(5),
    isAvailable: true, bookedSeat: [], soldSeat: [],
    slug: '2nk-shuttle-d5',
  },
];

exports.seedBuses = async () => {
  try {
    await Bus.deleteMany({});
    const buses = createBuses();
    await Bus.insertMany(buses, { validateBeforeSave: false });
    console.log(`✅ Buses seeded: ${buses.length} buses across 5 days added`);
  } catch (err) {
    console.error('Bus seed error:', err.message);
  }
};
